### ISSUE TITLE
Gestione Stampe

### ISSUE THREAD

**Issue by matteocattapan** [Consiglio-Regionale-della-Lombardia/PEM#7]
[23/06/2021] - [10:36:46] - [27] ERROR MonitoringLogger - CreaPDFCopertina Error-->
System.IO.IOException: The document has no pages.
   at iTextSharp.text.pdf.PdfPages.WritePageTree()
   at iTextSharp.text.pdf.PdfWriter.Close()
   at iTextSharp.text.pdf.PdfDocument.Close()
   at iTextSharp.text.pdf.PdfWriter.Close()
   at iTextSharp.text.DocWriter.Dispose()
   at PortaleRegione.GestioneStampe.PdfStamper.CreaPDFCopertina(String txtHTML, String pathcopertina) in C:\Git\PEM\Sorgenti modulo di stampa asincrona\PortaleRegione.GestioneStampe\PortaleRegione.GestioneStampe\PdfStamper.cs:line 147
[23/06/2021] - [10:36:46] - [27] ERROR MonitoringLogger - [26f7332e-8ba1-401f-a1a1-3033e6f8cf32] ERROR
System.IO.IOException: The document has no pages.
   at GeneraStampeJob.Worker.<Stampa>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GeneraStampeJob.Worker.<ExecuteAsync>d__6.MoveNext()

**Comment by matteocattapan** [comment]
Da verificare se problema risolto
